sudo: false # Stop annoying sudo warnings from travis

language: node_js
node_js:
  - v6 # Latest LTS

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn
  - yarn global add polymer-cli bower
  - bower install

# DEPLOY THINGS!
before_deploy:
  - polymer build
  - touch build/bundled/.nojekyll
  - cp manifest.json build/bundled/

# Publish to GitHub Pages
deploy:
  provider: pages
  repo: cansat-icarus/cansat-icarus.github.io
  skip_cleanup: true
  target_branch: master
  github_token: $GITHUB_TOKEN
  local_dir: build/bundled
  on:
    branch: master
    tags: true
