script: bash ./travis.sh
env:
  global:
  - GH_REF: github.com/cansat-icarus/cansat-icarus.github.io.git
  - secure: "rbdmP+GpUVDjftQR3ohzDjDTSliq0x+yId0HeStR+5zxVdCQT0XY2XPQYTPfA1q+eHLne6s79tqRH5EjoKvaXY8vT8EX4WV+lWhDBMlN4w0HS+QyYcxRN5wqFAyAnDlZu0YFRn0xRpAyNwtmAnsXnt/kjlm4Nm/bqHU8V+EoIWJsH1lvAmXqMgxvSgn8dZrX8EeEt1fJ+R3H2W2tXbuHnl5dvyUs60DHv0xy4dZk1AK5flLGs0Y6SIU6zVNbLmMbhukV/FrF97VciIBlEx6qHIh1XQ4OiJHBW8cxyvECLlb+G8u36pzngEcTRfKRBksTYWaqw58K4gOorH7ZEQlH2FP2bN0qf1fD2JYHB6AeBuRGLInAF/GF3i7tw+ZUTZ8VFZdrNA7w4bUivr0lHuOI35uug9ZiJ8skyTsaeMSKyPthh8ZDqAt+p7iVoFhdiDtljJo3f2iBFqa0BodMLYT6mYyzChi7I5FREK4kXk1wCPTbyRjLFq/kpA2MzvFpZNYfDiVLiU+4h4q/YJt1c7PwdwtHUZ4yJ176X59Kb+QsbTSI/qBJ3k7xRKkbG5QDstlMUl8bjKsbON8TAoFXHlxO0heglbjnkxffKZ8G1ksrbrUvQtg1HLV33IYSUn0nSE4MGfIWGtF/fyAS9y8GF3Chzve7i8tYbkRa3jM+688tyVg="
language: node_js
node_js:
  - "v4"
cache:
  directories:
    - node_modules
