# Logo
logo: #css/images/logo.png # Empty this to unset logo and show site title in the same place
avatar: /assets/images/logo/icarus.png

# Header
menu:
  home: .
  #archives: archives
  #categories: categories.html
  tags: tags.html
  partners: partners.html
  mission: mission.html
  about: about.html

# Content
fancybox: true

# Profile
profile: true # Whether to show profile bar
gravatar: false # Whether to use gravatar with the email. If you do, put your email address in your site's `_config.yml`.

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
  - profile
  - archive
thumbnail: true

# Contacts
contacts:
  facebook: 'https://www.facebook.com/Icarus-1662440837332463'
  instagram: 'https://www.instagram.com/icarus_esap/'
  github: 'https://github.com/cansat-icarus'
  rss: /:lang/atom.xml

# Links
links:
  Hexo: http://hexo.io

# CDN
cdn: # You can choose "useso" instead of "google apis"(default).

# Miscellaneous
google_site_verification:
google_analytics:
favicon: favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

partners:
  - name: "Alphasense"
    img_url: "http://www.alphasense.com/WEB1213/wp-content/themes/alphasense/assets/images/alphasense-logo.jpg"
    url: "http://www.alphasense.com"
  - name: ""
    img_url: "/assets/images/logo/LogoBEE_WhiteBackground.png"
    url: "https://beeverycreative.com/"
  - name: "Fusedminds"
    img_url: "/assets/images/logo/fusedminds.jpg"
    url: "http://www.fusedminds.pt/"
  - name: ""
    img_url: "https://d3nevzfk7ii3be.cloudfront.net/igi/nG1MvGbrC2wopi5H.standard"
    url: "https://www.ifixit.com/"
  - name: ""
    img_url: "/assets/images/logo/litoprint.png"
    url: "http://www.litoprint.pt/"
  - name: ""
    img_url: "/assets/images/logo/sugru.jpg"
    url: "http://www.sugru.com"
  - name: ""
    img_url: "http://www.loja.tek4all.org/img/tek4all-solucao-informatica-logo-1449616460.jpg"
    url: "http://www.loja.tek4all.org/"
  - name: ""
    img_url: "/assets/images/logo/ua.jpg"
    url: "http://www.ua.pt/"
